### ISSUE TITLE
The method isBlank() is undefined for the type String

### ISSUE THREAD

**Issue by tczauderna** [LSI-UniKonstanz/vanted#7]
The method isBlank() is undefined for the type String.

Commit #be0f9c1 changes 
`src/main/java/de/ipk_gatersleben/ag_nw/graffiti/plugins/gui/layout_control/dbe/PutIntoSidePanel.java` in line 35
from `tabtitle.equals("")` to `tabtitle.isBlank()`.

However, the `isBlank` method doesn't seem to be available in Java 8 and causes the error message mentioned above.

**Comment by dgarkov** [comment]
Thanks! It is now reverted back to using the isEmpty() method instead.
