### ISSUE TITLE
Merge/Review wiki additions

### ISSUE THREAD

**Issue by xnhp** [LSI-UniKonstanz/vanted#9]
Hi,

I just dug out some notes on VANTED internals that we took when working on the Pathway Matrix project. I think they would be a useful addition to the wiki.

Although you can access GitHub wikis as git repos, you cannot directly create pull requests. Instead, one can fork the repo and ask for a merge (i.e. the merger would pull from the forked repo into the local working copy and then push to the "official" wiki).

Please find my changes at [https://github.com/xnhp/vanted-wiki](https://github.com/xnhp/vanted-wiki).

Best,
Ben

**Comment by dgarkov** [comment]
Thank you, @xnhp! Closing the issue as resolved. The changes are part of the Wiki now, thanks to @niklas-groene.
